In [1]:
%load_ext autoreload
%autoreload 2
from holodeck.constants import MSOL, YR
from holodeck.utils import gaussian_freqs, pta_freqs
import numpy as np

Make sure we have consistency for the equivalent case to pta_freqs:

In [2]:
dur = 16*YR
gaussian_freqs(10,fmax=11/dur,dur=dur)
pta_freqs(dur=dur,num=10)

(array([1.98050549e-09, 3.96101098e-09, 5.94151647e-09, 7.92202195e-09,
        9.90252744e-09, 1.18830329e-08, 1.38635384e-08, 1.58440439e-08,
        1.78245494e-08, 1.98050549e-08]),
 array([9.90252744e-10, 2.97075823e-09, 4.95126372e-09, 6.93176921e-09,
        8.91227470e-09, 1.08927802e-08, 1.28732857e-08, 1.48537912e-08,
        1.68342967e-08, 1.88148021e-08, 2.07953076e-08]))

In [3]:
gaussian_centers, gaussian_edges = gaussian_freqs(10,fmax=11/dur,dur=dur)
len(gaussian_centers)

10

In [4]:
pta_centers, pta_edges = pta_freqs(dur=dur,num=10)
len(pta_centers)

10

In [5]:
pta_edges*dur

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [6]:
gaussian_edges*dur

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [7]:
np.allclose(pta_edges,gaussian_edges)

True

In [8]:
gaussian_freqs(100,fmax=11/dur,dur=dur)

(array([1.98050549e-09, 2.17855604e-09, 2.37660659e-09, 2.57465713e-09,
        2.77270768e-09, 2.97075823e-09, 3.16880878e-09, 3.36685933e-09,
        3.56490988e-09, 3.76296043e-09, 3.96101098e-09, 4.15906153e-09,
        4.35711207e-09, 4.55516262e-09, 4.75321317e-09, 4.95126372e-09,
        5.14931427e-09, 5.34736482e-09, 5.54541537e-09, 5.74346592e-09,
        5.94151647e-09, 6.13956701e-09, 6.33761756e-09, 6.53566811e-09,
        6.73371866e-09, 6.93176921e-09, 7.12981976e-09, 7.32787031e-09,
        7.52592086e-09, 7.72397140e-09, 7.92202195e-09, 8.12007250e-09,
        8.31812305e-09, 8.51617360e-09, 8.71422415e-09, 8.91227470e-09,
        9.11032525e-09, 9.30837580e-09, 9.50642634e-09, 9.70447689e-09,
        9.90252744e-09, 1.01005780e-08, 1.02986285e-08, 1.04966791e-08,
        1.06947296e-08, 1.08927802e-08, 1.10908307e-08, 1.12888813e-08,
        1.14869318e-08, 1.16849824e-08, 1.18830329e-08, 1.20810835e-08,
        1.22791340e-08, 1.24771846e-08, 1.26752351e-08, 1.287328